#pragma once

// Lit. Every single key in the American Standard code for Information Exchange
// ft. my rapidly dwindling sanity
#define KEY_NULL 0x00 // NULL
#define KEY_STOH 0x01 // START OF HEADING
#define KEY_STOX 0x02 // START OF TEXT
#define KEY_ENOX 0x03 // END OF TEXT
#define KEY_ENOT 0x04 // END OF TRANSMISSION
#define KEY_ENQU 0x05 // ENQUIRY
#define KEY_ACKN 0x06 // ACKNOWLEDGE
#define KEY_BELL 0x07 // BELL
#define KEY_BACK 0x08 // BACKSPACE
#define KEY_HORT 0x09 // HORIZONTAL TAB
#define KEY_LINF 0x0A // LINE FEED
#define KEY_LINT 0x0B // VERTICAL TAB
#define KEY_FORF 0x0C // FORM FEED
#define KEY_CARR 0x0D // CARRIAGE RETURN
#define KEY_SHFO 0x0E // SHIFT OUT
#define KEY_SHOI 0x0F // SHIFT IN
#define KEY_DALN 0x10 // DATA LINK ESCAPE
#define KEY_DVC1 0x11 // DEVICE CONTROL 1
#define KEY_DVC2 0x12 // DEVICE CONTROL 2
#define KEY_DVC3 0x13 // DEVICE CONTROL 3
#define KEY_DVC4 0x14 // DEVICE CONTROL 4
#define KEY_NACK 0x15 // NEGATIVE ACKNOWLEDGE
#define KEY_SYNC 0x16 // SYNCHRONIZE
#define KEY_EOTB 0x17 // END OF TRANSMISSION BLOCK
#define KEY_CANC 0x18 // CANCEL
#define KEY_EOMD 0x19 // END OF MEDIUM
#define KEY_SUBS 0x1A // SUBSTITUTE
#define KEY_ESCP 0x1B // ESCAPE
#define KEY_FSEP 0x1C // FILE SEPARATOR
#define KEY_GSEP 0x1D // GROUP SEPARATOR
#define KEY_RSEC 0x1E // RECORD SEPARATOR
#define KEY_USEC 0x1F // UNIT SEPARATOR

#define KEY_SPCE 0x20 // SPACE
#define KEY_EXCL 0x21 // EXCLAMATION MARK
#define KEY_DUQO 0x22 // DOUBLE QUOTE
#define KEY_NUMS 0x23 // NUMBER SYMBOL
#define KEY_DOLS 0x24 // DOLLAR SYMBOL
#define KEY_PERS 0x25 // PERCENT SYMBOL
#define KEY_AMPR 0x26 // AMPERSAND
#define KEY_SINQ 0x27 // SINGLE QUOTE
#define KEY_LEFP 0x28 // LEFT PARENTHESIS
#define KEY_RIGP 0x29 // RIGHT PARENTHESIS
#define KEY_ASTS 0x2A // ASTERISK SYMBOL
#define KEY_PLUS 0x2B // PLUS SYMBOL
#define KEY_COMA 0x2C // COMMA
#define KEY_MIND 0x2D // MINUS-DASH
#define KEY_PERD 0x2E // PERIOD
#define KEY_FORS 0x2F // FORWARD SLASH

#define KEY_0 0x30 // ZERO
#define KEY_1 0x31 // ONE
#define KEY_2 0x32 // TWO
#define KEY_3 0x33 // THREE
#define KEY_4 0x34 // FOUR
#define KEY_5 0x35 // FIVE
#define KEY_6 0x36 // SIX
#define KEY_7 0x37 // SEVEN
#define KEY_8 0x38 // EIGHT
#define KEY_9 0x39 // NINE

#define KEY_COLN 0x3A // COLON
#define KEY_SEMC 0x3B // SEMICOLON
#define KEY_LESS 0x3C // LESS THAN SYMBOL
#define KEY_EQUS 0x3D // EQUALITY SYMBOL
#define KEY_GRES 0x3E // GREATER THAN SYMBOL
#define KEY_QUES 0x3F // QUESTION MARK
#define KEY_ATSM 0x40 // AT SYMBOL

#define KEY_CAPT_A 0x41 // CAPITAL A
#define KEY_CAPT_B 0x42 // CAPITAL B
#define KEY_CAPT_C 0x43 // CAPITAL C
#define KEY_CAPT_D 0x44 // CAPITAL D
#define KEY_CAPT_E 0x45 // CAPITAL E
#define KEY_CAPT_F 0x46 // CAPITAL F
#define KEY_CAPT_G 0x47 // CAPITAL G
#define KEY_CAPT_H 0x48 // CAPITAL H
#define KEY_CAPT_I 0x49 // CAPITAL I
#define KEY_CAPT_J 0x4A // CAPITAL J
#define KEY_CAPT_K 0x4B // CAPITAL K
#define KEY_CAPT_L 0x4C // CAPITAL L
#define KEY_CAPT_M 0x4D // CAPITAL M
#define KEY_CAPT_N 0x4E // CAPITAL N
#define KEY_CAPT_O 0x4F // CAPITAL O
#define KEY_CAPT_P 0x50 // CAPITAL P
#define KEY_CAPT_Q 0x51 // CAPITAL Q
#define KEY_CAPT_R 0x52 // CAPITAL R
#define KEY_CAPT_S 0x53 // CAPITAL S
#define KEY_CAPT_T 0x54 // CAPITAL T
#define KEY_CAPT_U 0x55 // CAPITAL U
#define KEY_CAPT_V 0x56 // CAPITAL V
#define KEY_CAPT_W 0x57 // CAPITAL W
#define KEY_CAPT_X 0x58 // CAPITAL X
#define KEY_CAPT_Y 0x59 // CAPITAL Y
#define KEY_CAPT_Z 0x5A // CAPITAL Z

#define KEY_LSQB 0x5B // LEFT SQUARE BRACKET
#define KEY_BACS 0x5C // BACKSLASH
#define KEY_RSQB 0x5D // RIGHT SQUARE BRACKET
#define KEY_CART 0x5E // CARET
#define KEY_UNDS 0x5F // UNDERSCORE
#define KEY_ACNT 0x60 // ACCENT

#define KEY_LOWR_A 0x61 // LOWERCASE A
#define KEY_LOWR_B 0x62 // LOWERCASE B
#define KEY_LOWR_C 0x63 // LOWERCASE C
#define KEY_LOWR_D 0x64 // LOWERCASE D
#define KEY_LOWR_E 0x65 // LOWERCASE E
#define KEY_LOWR_F 0x66 // LOWERCASE F
#define KEY_LOWR_G 0x67 // LOWERCASE G
#define KEY_LOWR_H 0x68 // LOWERCASE H
#define KEY_LOWR_I 0x69 // LOWERCASE I
#define KEY_LOWR_J 0x6A // LOWERCASE J
#define KEY_LOWR_K 0x6B // LOWERCASE K
#define KEY_LOWR_L 0x6C // LOWERCASE L
#define KEY_LOWR_M 0x6D // LOWERCASE M
#define KEY_LOWR_N 0x6E // LOWERCASE N
#define KEY_LOWR_O 0x6F // LOWERCASE O
#define KEY_LOWR_P 0x70 // LOWERCASE P
#define KEY_LOWR_Q 0x71 // LOWERCASE Q
#define KEY_LOWR_R 0x72 // LOWERCASE R
#define KEY_LOWR_S 0x73 // LOWERCASE S
#define KEY_LOWR_T 0x74 // LOWERCASE T
#define KEY_LOWR_U 0x75 // LOWERCASE U
#define KEY_LOWR_V 0x76 // LOWERCASE V
#define KEY_LOWR_W 0x77 // LOWERCASE W
#define KEY_LOWR_X 0x78 // LOWERCASE X
#define KEY_LOWR_Y 0x79 // LOWERCASE Y
#define KEY_LOWR_Z 0x7A // LOWERCASE Z

#define KEY_LCRB 0x7B // LEFT CURLY BRACKET
#define KEY_VERB 0x7C // VERTICAL BAR
#define KEY_RCRB 0x7D // RIGHT CURLY BRACKET
#define KEY_TILD 0x7E // TILDE

#define KEY_DELT 0x7F // DELETE